apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: publisher
  name: publisher
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: publisher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - image: service:local
        imagePullPolicy: IfNotPresent
        args:
          - "serve"
          - "publisher"
          - "--nats"
          - "nats://nats:4222"
        name: service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: publisher
  name: publisher
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: publisher
  sessionAffinity: None
  type: ClusterIP
